# Generated by Django 2.1.5 on 2019-01-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='q',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='w',
            field=models.IntegerField(default=0),
        ),
    ]
